name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    name: Code quality checks for Veld
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # NOTE: Keep versions in line with .pre-commit-config.yaml

      - name: Run black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./veld ./tests"
          version: "24.2.0"

      - name: Run isort
        uses: jamescurtin/isort-action@master
        with:
          isortVersion: "5.12.0"

      - name: Run ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./veld ./tests"
          version: "v0.2.2"

  python:
    needs: [code-quality]
    name: Unit tests for Veld
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Can add others if deemed necessary
        os: [ 'ubuntu-latest' ]
        # minimal and latest
        py: [ '3.8', '3.12' ]

    steps:
      - name: Install Python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run unit tests
        run: make test_direct
